# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap]

# feed settings
title:		     "{{ site.data.settings.title }} | {{ site.data.settings.tagline }}"

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - yarn.lock
  - README.md 