title: kelsy gagnebin
tagline:  product designer
author:
  name: 'kelsy michael gagnebin'
  # twitter:  _kelsymichael

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: 'UA-64580274-1'

menu:
# - {name: 'Work', url: 'work.html'}
- {name: '(Mini)Case-Study', url: 'caseStudy.html'}
- {name: 'About', url: 'about.html'}
# - {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/kelsymichael'}
# - {icon: 'twitter', link: 'https://twitter.com/'}
# - {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/kelsygagnebin'}
- {icon: 'envelope', link: 'mailto:kelsymichael@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
